import Head from 'next/head'
import NavComponent from '../NavComponent/NavComponent'

export default function Layout({ children }) {
    return (
      <>
        <div className="container mx-auto bg-[url('/bg.jpg')] bg-no-repeat border-solid border-1" style={{maxWidth: 50 + '%'}}>
        <Head>
            <title>Goals App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <NavComponent/>
        <main className="main-bg mt-60 p-2">  
           {children}
        </main>
    
    </div>
      </>
    )
  }